

####################################
######### Configure these ##########
####################################

# name must not contain special characters like spaces, /
# alpha numeric only, -, _
name: "Public" 

# uncomment the following when usgin basic authentication with the server
basic_auth:
  user: johndoe
  pass: AKkmyqnJvR5SsRzNn8eF

kms:
  url: "https://cybexp-priv.ignaciochg.com:5002"
backend_server:
  url: "https://cybexp-priv.ignaciochg.com:5001"


####################################
########## Dev settings ############
####################################

debug: 
  enabled: False
  process_only_one: False
  

####################################
##### no need to change below ######
####################################

key_files:
  de: /secrets/de.bin
  ore: /secrets/ore.bin
  cpabe_pub: /secrets/cpabe_pub.bin
  cpabe_secret: /secrets/cpabe_secret.bin





####################################
############# Query ################
########### Deprecated #############
####################################

# # query: "165.227.91.185"
# query: "test"
# # times in UNIX int
# from_time: 1
# to_time: 5000

# inclusive_left: False
# inclusive_right: False

