debug: 
  enabled: True
  process_only_one: True
  
kms:
  url: "http://192.168.1.101:5002"
backend_server:
  url: "http://192.168.1.101:5001"
  #max_post_retries: 5

key_files:
  de: /secrets/de.bin
  ore: /secrets/ore.bin
  cpabe_pub: /secrets/cpabe_pub.bin
  cpabe_secret: /secrets/cpabe_secret.bin

# name must not contain special characters like spaces, /
# alpha numeric only, -, _
name: "official_org_name" 


query: "165.227.91.185"
# times in UNIX int
#from_time: 
#to_time: 

