

####################################
######### Configure these ##########
####################################

# Use /login endpoint@KMS to get kms_access_key
# Alternatively use provided login script
# kms_access_key: "kms_access_key" 
kms_access_key: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTYyNTU5MTc4MiwianRpIjoiYzU5MTcwMjItZTUyNi00Y2M1LWE2YzgtNmM5MWMzZTVlMjNkIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InRlc3QyIiwibmJmIjoxNjI1NTkxNzgyfQ.F1TrcphwY1OnmnWV5HbZElW3sctuHxsHIGbfy13qMhU" 

# uncomment the following (3 lines) when using basic authentication with the server
# basic_auth:
#   user: 'username_here'
#   pass: 'password_here'

kms:
  url: "http://192.168.1.101:5002"
backend_server:
  url: "http://192.168.1.101:5001"


####################################
########## Dev settings ############
####################################

debug: 
  vebose: True
  process_only_one: False

  

####################################
##### no need to change below ######
####################################

key_files:
  de: /secrets/de.bin
  ore: /secrets/ore.bin
  ore_params: /secrets/ore_params.bin
  cpabe_pub: /secrets/cpabe_pub.bin
  cpabe_secret: /secrets/cpabe_secret.bin

